services:

  nginx:
    restart: unless-stopped
    image: nginx:1.27
    ports:
      - "5000:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - app:app
    command: /bin/bash -c "nginx -g 'daemon off;'"

  redis:
    restart: unless-stopped
    image: redis:7.4

  app:
    restart: unless-stopped
    build: .
    links:
      - redis:redis
    command: gunicorn --bind 0.0.0.0:5001 datahub.wsgi:app
    deploy:
      replicas: 3
